Fixed `clean` target in `Makefile`
As there are no longer any Go files in the project root we need to
point go clean towards something that does contain Go files. Not doing
this will result in an error:

  $ go clean
  can't load package: package github.com/fluxcd/helm-operator: unknown
  import path "github.com/fluxcd/helm-operator": cannot find module
  providing package github.com/fluxcd/helm-operator